#!/bin/bash
case "`grep DISTRIB_CODENAME /etc/*-release | awk -F '=' '{print $2}'`" in
      trusty)
              if [ "$(whoami)" != "root" ]
                 then
                  echo "You need to login as root to use this script! Sorry!";
                 exit 1
              fi 
              
             apt-get update; apt-get upgrade -y; apt-get dist-upgrade -y; apt-get autoremove -y;
             apt-get install build-essential libssl-dev curl nano wget zip unzip git -y
             apt-get purge --remove nginx -y
             apt-get purge --remove apache2 -y
             mkdir -p /tmp; cd /tmp
             wget https://raw.githubusercontent.com/systemroot/my-nginx/master/nginx-as-firewall/setup
             chmod +x setup
             ./setup clean
             clear
             ./setup install
             clear
             ./setup fix
             ./setup iphp
             
      ;;



























      centos)
             yum -y update; yum -y upgrade
             yum install epel-release wget curl git zip unzip -y
             yum remove httpd -y
             yum remove apache2 -y
             yum remove nginx -y
      ;;
esac
