#!/bin/bash

sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8
sudo add-apt-repository 'deb [arch=amd64] http://mirror.23media.de/mariadb/repo/10.3/ubuntu bionic main'
apt-get update; apt-get upgrade -y; apt-get dist-upgrade -y; apt-get autoremove -y

sudo apt install mariadb-server

mysql_secure_installation
